// Package apiv2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiv2

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateJobSiteRequest defines model for CreateJobSiteRequest.
type CreateJobSiteRequest struct {
	Location string `json:"location"`
	Name     string `json:"name"`
}

// CreateScheduleRequest defines model for CreateScheduleRequest.
type CreateScheduleRequest struct {
	EndDate time.Time `json:"endDate"`

	// Id Optional schedule ID. If omitted, one will be generated.
	Id        *string   `json:"id,omitempty"`
	StartDate time.Time `json:"startDate"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Description      string    `json:"description"`
	Name             string    `json:"name"`
	PlannedEndTime   time.Time `json:"plannedEndTime"`
	PlannedStartTime time.Time `json:"plannedStartTime"`
	ScheduleId       string    `json:"scheduleId"`
	WorkerId         string    `json:"workerId"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// JobSite defines model for JobSite.
type JobSite struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Location  *string    `json:"location,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// RecordAttendanceRequest defines model for RecordAttendanceRequest.
type RecordAttendanceRequest struct {
	CheckInTime time.Time `json:"checkInTime"`
	JobSiteId   string    `json:"jobSiteId"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	EndDate   *time.Time `json:"endDate,omitempty"`
	Id        *string    `json:"id,omitempty"`
	JobSiteId *string    `json:"jobSiteId,omitempty"`
	StartDate *time.Time `json:"startDate,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Task defines model for Task.
type Task struct {
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	Description      *string    `json:"description,omitempty"`
	Id               *string    `json:"id,omitempty"`
	Name             *string    `json:"name,omitempty"`
	PlannedEndTime   *time.Time `json:"plannedEndTime,omitempty"`
	PlannedStartTime *time.Time `json:"plannedStartTime,omitempty"`
	ScheduleId       *string    `json:"scheduleId,omitempty"`

	// Status Current task status (PENDING, IN_PROGRESS, BLOCKED, COMPLETED)
	Status    *string    `json:"status,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	WorkerId  *string    `json:"workerId,omitempty"`
}

// UpdateAttendanceRequest defines model for UpdateAttendanceRequest.
type UpdateAttendanceRequest struct {
	CheckOutTime time.Time          `json:"checkOutTime"`
	Date         openapi_types.Date `json:"date"`
	JobSiteId    string             `json:"jobSiteId"`
}

// UpdateTaskStatusRequest defines model for UpdateTaskStatusRequest.
type UpdateTaskStatusRequest struct {
	Status string `json:"status"`
}

// ValidateScheduleRequest defines model for ValidateScheduleRequest.
type ValidateScheduleRequest struct {
	EndDate   time.Time `json:"endDate"`
	StartDate time.Time `json:"startDate"`
}

// WorkerAttendance defines model for WorkerAttendance.
type WorkerAttendance struct {
	CheckInTime  *time.Time          `json:"checkInTime,omitempty"`
	CheckOutTime *time.Time          `json:"checkOutTime,omitempty"`
	CreatedAt    *time.Time          `json:"createdAt,omitempty"`
	Date         *openapi_types.Date `json:"date,omitempty"`
	JobSiteId    *string             `json:"jobSiteId,omitempty"`
	UpdatedAt    *time.Time          `json:"updatedAt,omitempty"`
	WorkerId     *string             `json:"workerId,omitempty"`
}

// GetSiteAttendanceParams defines parameters for GetSiteAttendance.
type GetSiteAttendanceParams struct {
	// Date Date (YYYY-MM-DD). Defaults to today's date.
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// GetWorkerTasksParams defines parameters for GetWorkerTasks.
type GetWorkerTasksParams struct {
	// Date Date for which to retrieve tasks (YYYY-MM-DD). Defaults to today's date.
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// CreateJobSiteJSONRequestBody defines body for CreateJobSite for application/json ContentType.
type CreateJobSiteJSONRequestBody = CreateJobSiteRequest

// CreateScheduleJSONRequestBody defines body for CreateSchedule for application/json ContentType.
type CreateScheduleJSONRequestBody = CreateScheduleRequest

// ValidateScheduleOverlapJSONRequestBody defines body for ValidateScheduleOverlap for application/json ContentType.
type ValidateScheduleOverlapJSONRequestBody = ValidateScheduleRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskStatusJSONRequestBody defines body for UpdateTaskStatus for application/json ContentType.
type UpdateTaskStatusJSONRequestBody = UpdateTaskStatusRequest

// RecordWorkerAttendanceJSONRequestBody defines body for RecordWorkerAttendance for application/json ContentType.
type RecordWorkerAttendanceJSONRequestBody = RecordAttendanceRequest

// UpdateWorkerAttendanceJSONRequestBody defines body for UpdateWorkerAttendance for application/json ContentType.
type UpdateWorkerAttendanceJSONRequestBody = UpdateAttendanceRequest
