// Package apiv2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiv2

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TaskStatus.
const (
	TaskStatusBLOCKED    TaskStatus = "BLOCKED"
	TaskStatusCOMPLETED  TaskStatus = "COMPLETED"
	TaskStatusINPROGRESS TaskStatus = "IN_PROGRESS"
	TaskStatusPENDING    TaskStatus = "PENDING"
)

// Defines values for UpdateTaskStatusRequestStatus.
const (
	UpdateTaskStatusRequestStatusBLOCKED    UpdateTaskStatusRequestStatus = "BLOCKED"
	UpdateTaskStatusRequestStatusCOMPLETED  UpdateTaskStatusRequestStatus = "COMPLETED"
	UpdateTaskStatusRequestStatusINPROGRESS UpdateTaskStatusRequestStatus = "IN_PROGRESS"
	UpdateTaskStatusRequestStatusPENDING    UpdateTaskStatusRequestStatus = "PENDING"
)

// AttendanceRecord defines model for AttendanceRecord.
type AttendanceRecord struct {
	CheckInTime  time.Time          `json:"checkInTime"`
	CheckOutTime *time.Time         `json:"checkOutTime,omitempty"`
	CreatedAt    *time.Time         `json:"createdAt,omitempty"`
	Date         openapi_types.Date `json:"date"`
	JobSiteId    string             `json:"jobSiteId"`
	UpdatedAt    *time.Time         `json:"updatedAt,omitempty"`
	WorkerId     string             `json:"workerId"`
}

// CreateJobSiteRequest defines model for CreateJobSiteRequest.
type CreateJobSiteRequest struct {
	Location string `json:"location"`
	Name     string `json:"name"`
}

// CreateScheduleRequest defines model for CreateScheduleRequest.
type CreateScheduleRequest struct {
	EndDate   time.Time `json:"endDate"`
	Id        *string   `json:"id,omitempty"`
	StartDate time.Time `json:"startDate"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Description      string    `json:"description"`
	Name             string    `json:"name"`
	PlannedEndTime   time.Time `json:"planned_end_time"`
	PlannedStartTime time.Time `json:"planned_start_time"`
	ScheduleId       string    `json:"schedule_id"`
	WorkerId         string    `json:"worker_id"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// JobSite defines model for JobSite.
type JobSite struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        string     `json:"id"`
	Location  string     `json:"location"`
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// RecordAttendanceRequest defines model for RecordAttendanceRequest.
type RecordAttendanceRequest struct {
	CheckInTime time.Time `json:"checkInTime"`
	JobSiteId   string    `json:"jobSiteId"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	EndDate   time.Time  `json:"endDate"`
	Id        string     `json:"id"`
	JobSiteId string     `json:"jobSiteId"`
	StartDate time.Time  `json:"startDate"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Task defines model for Task.
type Task struct {
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	Description      string     `json:"description"`
	Id               string     `json:"id"`
	Name             string     `json:"name"`
	PlannedEndTime   time.Time  `json:"plannedEndTime"`
	PlannedStartTime time.Time  `json:"plannedStartTime"`
	ScheduleId       string     `json:"scheduleId"`
	Status           TaskStatus `json:"status"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
	WorkerId         string     `json:"workerId"`
}

// TaskStatus defines model for Task.Status.
type TaskStatus string

// UpdateAttendanceRequest defines model for UpdateAttendanceRequest.
type UpdateAttendanceRequest struct {
	CheckOutTime time.Time          `json:"checkOutTime"`
	Date         openapi_types.Date `json:"date"`
	JobSiteId    string             `json:"jobSiteId"`
}

// UpdateTaskStatusRequest defines model for UpdateTaskStatusRequest.
type UpdateTaskStatusRequest struct {
	Status UpdateTaskStatusRequestStatus `json:"status"`
}

// UpdateTaskStatusRequestStatus defines model for UpdateTaskStatusRequest.Status.
type UpdateTaskStatusRequestStatus string

// ValidateScheduleRequest defines model for ValidateScheduleRequest.
type ValidateScheduleRequest struct {
	EndDate   time.Time `json:"endDate"`
	StartDate time.Time `json:"startDate"`
}

// DateParam defines model for DateParam.
type DateParam = openapi_types.Date

// JobSiteId defines model for JobSiteId.
type JobSiteId = string

// TaskId defines model for TaskId.
type TaskId = string

// WorkerId defines model for WorkerId.
type WorkerId = string

// GetSiteAttendanceParams defines parameters for GetSiteAttendance.
type GetSiteAttendanceParams struct {
	Date *DateParam `form:"date,omitempty" json:"date,omitempty"`
}

// GetWorkerTasksParams defines parameters for GetWorkerTasks.
type GetWorkerTasksParams struct {
	Date *DateParam `form:"date,omitempty" json:"date,omitempty"`
}

// CreateJobSiteJSONRequestBody defines body for CreateJobSite for application/json ContentType.
type CreateJobSiteJSONRequestBody = CreateJobSiteRequest

// CreateScheduleJSONRequestBody defines body for CreateSchedule for application/json ContentType.
type CreateScheduleJSONRequestBody = CreateScheduleRequest

// ValidateScheduleOverlapJSONRequestBody defines body for ValidateScheduleOverlap for application/json ContentType.
type ValidateScheduleOverlapJSONRequestBody = ValidateScheduleRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskStatusJSONRequestBody defines body for UpdateTaskStatus for application/json ContentType.
type UpdateTaskStatusJSONRequestBody = UpdateTaskStatusRequest

// RecordWorkerAttendanceJSONRequestBody defines body for RecordWorkerAttendance for application/json ContentType.
type RecordWorkerAttendanceJSONRequestBody = RecordAttendanceRequest

// UpdateWorkerAttendanceJSONRequestBody defines body for UpdateWorkerAttendance for application/json ContentType.
type UpdateWorkerAttendanceJSONRequestBody = UpdateAttendanceRequest
