// Package apiv2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiv2

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new job site
	// (POST /job-sites)
	CreateJobSite(c *gin.Context)
	// Retrieve a job site by ID
	// (GET /job-sites/{id})
	GetJobSite(c *gin.Context, id JobSiteId)
	// Retrieve attendance records for a job site on a specific date
	// (GET /job-sites/{id}/attendance)
	GetSiteAttendance(c *gin.Context, id JobSiteId, params GetSiteAttendanceParams)
	// Retrieve all schedules for a job site
	// (GET /job-sites/{id}/schedules)
	GetSchedules(c *gin.Context, id JobSiteId)
	// Create a new schedule for a job site
	// (POST /job-sites/{id}/schedules)
	CreateSchedule(c *gin.Context, id JobSiteId)
	// Retrieve active schedules for a job site
	// (GET /job-sites/{id}/schedules/active)
	GetActiveSchedules(c *gin.Context, id JobSiteId)
	// Retrieve upcoming schedules for a job site
	// (GET /job-sites/{id}/schedules/upcoming)
	GetUpcomingSchedules(c *gin.Context, id JobSiteId)
	// Validate schedule overlap for a job site
	// (POST /job-sites/{id}/schedules/validate)
	ValidateScheduleOverlap(c *gin.Context, id JobSiteId)
	// Create a new task for a job site
	// (POST /job-sites/{id}/tasks)
	CreateTask(c *gin.Context, id JobSiteId)
	// Retrieve a schedule by its ID
	// (GET /schedules/{id})
	GetSchedule(c *gin.Context, id string)
	// Retrieve task details by ID
	// (GET /tasks/{id})
	GetTask(c *gin.Context, id TaskId)
	// Update the status of a task
	// (PUT /tasks/{id}/status)
	UpdateTaskStatus(c *gin.Context, id TaskId)
	// Retrieve tasks for a worker on a specific date
	// (GET /workers/{id}/tasks)
	GetWorkerTasks(c *gin.Context, id string, params GetWorkerTasksParams)
	// Record worker attendance (check-in)
	// (POST /workers/{workerID}/attendance)
	RecordWorkerAttendance(c *gin.Context, workerID WorkerId)
	// Update worker attendance (check-out)
	// (PUT /workers/{workerID}/attendance)
	UpdateWorkerAttendance(c *gin.Context, workerID WorkerId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateJobSite operation middleware
func (siw *ServerInterfaceWrapper) CreateJobSite(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateJobSite(c)
}

// GetJobSite operation middleware
func (siw *ServerInterfaceWrapper) GetJobSite(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobSiteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJobSite(c, id)
}

// GetSiteAttendance operation middleware
func (siw *ServerInterfaceWrapper) GetSiteAttendance(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobSiteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSiteAttendanceParams

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameter("form", true, false, "date", c.Request.URL.Query(), &params.Date)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter date: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSiteAttendance(c, id, params)
}

// GetSchedules operation middleware
func (siw *ServerInterfaceWrapper) GetSchedules(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobSiteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSchedules(c, id)
}

// CreateSchedule operation middleware
func (siw *ServerInterfaceWrapper) CreateSchedule(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobSiteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSchedule(c, id)
}

// GetActiveSchedules operation middleware
func (siw *ServerInterfaceWrapper) GetActiveSchedules(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobSiteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActiveSchedules(c, id)
}

// GetUpcomingSchedules operation middleware
func (siw *ServerInterfaceWrapper) GetUpcomingSchedules(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobSiteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUpcomingSchedules(c, id)
}

// ValidateScheduleOverlap operation middleware
func (siw *ServerInterfaceWrapper) ValidateScheduleOverlap(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobSiteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateScheduleOverlap(c, id)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobSiteId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTask(c, id)
}

// GetSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetSchedule(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSchedule(c, id)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTask(c, id)
}

// UpdateTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateTaskStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTaskStatus(c, id)
}

// GetWorkerTasks operation middleware
func (siw *ServerInterfaceWrapper) GetWorkerTasks(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkerTasksParams

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameter("form", true, false, "date", c.Request.URL.Query(), &params.Date)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter date: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkerTasks(c, id, params)
}

// RecordWorkerAttendance operation middleware
func (siw *ServerInterfaceWrapper) RecordWorkerAttendance(c *gin.Context) {

	var err error

	// ------------- Path parameter "workerID" -------------
	var workerID WorkerId

	err = runtime.BindStyledParameterWithOptions("simple", "workerID", c.Param("workerID"), &workerID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workerID: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RecordWorkerAttendance(c, workerID)
}

// UpdateWorkerAttendance operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkerAttendance(c *gin.Context) {

	var err error

	// ------------- Path parameter "workerID" -------------
	var workerID WorkerId

	err = runtime.BindStyledParameterWithOptions("simple", "workerID", c.Param("workerID"), &workerID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workerID: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateWorkerAttendance(c, workerID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/job-sites", wrapper.CreateJobSite)
	router.GET(options.BaseURL+"/job-sites/:id", wrapper.GetJobSite)
	router.GET(options.BaseURL+"/job-sites/:id/attendance", wrapper.GetSiteAttendance)
	router.GET(options.BaseURL+"/job-sites/:id/schedules", wrapper.GetSchedules)
	router.POST(options.BaseURL+"/job-sites/:id/schedules", wrapper.CreateSchedule)
	router.GET(options.BaseURL+"/job-sites/:id/schedules/active", wrapper.GetActiveSchedules)
	router.GET(options.BaseURL+"/job-sites/:id/schedules/upcoming", wrapper.GetUpcomingSchedules)
	router.POST(options.BaseURL+"/job-sites/:id/schedules/validate", wrapper.ValidateScheduleOverlap)
	router.POST(options.BaseURL+"/job-sites/:id/tasks", wrapper.CreateTask)
	router.GET(options.BaseURL+"/schedules/:id", wrapper.GetSchedule)
	router.GET(options.BaseURL+"/tasks/:id", wrapper.GetTask)
	router.PUT(options.BaseURL+"/tasks/:id/status", wrapper.UpdateTaskStatus)
	router.GET(options.BaseURL+"/workers/:id/tasks", wrapper.GetWorkerTasks)
	router.POST(options.BaseURL+"/workers/:workerID/attendance", wrapper.RecordWorkerAttendance)
	router.PUT(options.BaseURL+"/workers/:workerID/attendance", wrapper.UpdateWorkerAttendance)
}
