openapi: 3.0.3
info:
  title: Alertmanager Webhook Logger
  version: "1.0.0"

paths:
  /alerts:
    post:
      operationId: PostAlerts
      summary: Receives Alertmanager webhook payload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertmanagerWebhook'
      responses:
        '200':
          description: Successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    AlertmanagerWebhook:
      type: object
      properties:
        version:
          type: string
          example: "4"
        groupKey:
          type: string
          description: Key identifying the group of alerts
        truncatedAlerts:
          type: integer
          description: Number of truncated alerts if max_alerts is set
        status:
          type: string
          description: "firing or resolved"
        receiver:
          type: string
        groupLabels:
          type: object
          additionalProperties: true
        commonLabels:
          type: object
          additionalProperties: true
        commonAnnotations:
          type: object
          additionalProperties: true
        externalURL:
          type: string
          description: Link back to the Alertmanager
        alerts:
          type: array
          items:
            $ref: '#/components/schemas/Alert'
      required:
        - version
        - status
        - alerts

    Alert:
      type: object
      properties:
        status:
          type: string
          description: "firing or resolved"
        labels:
          type: object
          additionalProperties: true
        annotations:
          type: object
          additionalProperties: true
        startsAt:
          type: string
          format: date-time
        endsAt:
          type: string
          format: date-time
        generatorURL:
          type: string
        fingerprint:
          type: string

    Response:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    Error:
      type: object
      properties:
        error:
          type: string
      required:
        - error
