// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"
)

// Alert defines model for Alert.
type Alert struct {
	Annotations  *map[string]interface{} `json:"annotations,omitempty"`
	EndsAt       *time.Time              `json:"endsAt,omitempty"`
	Fingerprint  *string                 `json:"fingerprint,omitempty"`
	GeneratorURL *string                 `json:"generatorURL,omitempty"`
	Labels       *map[string]interface{} `json:"labels,omitempty"`
	StartsAt     *time.Time              `json:"startsAt,omitempty"`

	// Status firing or resolved
	Status *string `json:"status,omitempty"`
}

// AlertmanagerWebhook defines model for AlertmanagerWebhook.
type AlertmanagerWebhook struct {
	Alerts            []Alert                 `json:"alerts"`
	CommonAnnotations *map[string]interface{} `json:"commonAnnotations,omitempty"`
	CommonLabels      *map[string]interface{} `json:"commonLabels,omitempty"`

	// ExternalURL Link back to the Alertmanager
	ExternalURL *string `json:"externalURL,omitempty"`

	// GroupKey Key identifying the group of alerts
	GroupKey    *string                 `json:"groupKey,omitempty"`
	GroupLabels *map[string]interface{} `json:"groupLabels,omitempty"`
	Receiver    *string                 `json:"receiver,omitempty"`

	// Status firing or resolved
	Status string `json:"status"`

	// TruncatedAlerts Number of truncated alerts if max_alerts is set
	TruncatedAlerts *int   `json:"truncatedAlerts,omitempty"`
	Version         string `json:"version"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Response defines model for Response.
type Response struct {
	Message string `json:"message"`
}

// PostAlertsJSONRequestBody defines body for PostAlerts for application/json ContentType.
type PostAlertsJSONRequestBody = AlertmanagerWebhook
