// Package apiv2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiv2

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TaskStatus.
const (
	BLOCKED    TaskStatus = "BLOCKED"
	COMPLETED  TaskStatus = "COMPLETED"
	INPROGRESS TaskStatus = "IN_PROGRESS"
	PENDING    TaskStatus = "PENDING"
)

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// HistoricalTaskInfo defines model for HistoricalTaskInfo.
type HistoricalTaskInfo struct {
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	Description      *string    `json:"description,omitempty"`
	Id               *string    `json:"id,omitempty"`
	JobSiteId        *string    `json:"jobSiteId,omitempty"`
	Name             *string    `json:"name,omitempty"`
	PlannedEndTime   *time.Time `json:"plannedEndTime,omitempty"`
	PlannedStartTime *time.Time `json:"plannedStartTime,omitempty"`
	Status           *string    `json:"status,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

// ProductivityStats defines model for ProductivityStats.
type ProductivityStats struct {
	AvgCompletionTime *string  `json:"avgCompletionTime,omitempty"`
	BlockedTasks      *int     `json:"blockedTasks,omitempty"`
	CompletedTasks    *int     `json:"completedTasks,omitempty"`
	CompletionRate    *float64 `json:"completionRate,omitempty"`
	TotalTasks        *int     `json:"totalTasks,omitempty"`
}

// SiteProductivityMetrics defines model for SiteProductivityMetrics.
type SiteProductivityMetrics struct {
	DailyStats *map[string]SiteProductivityStats `json:"dailyStats,omitempty"`
	EndDate    *time.Time                        `json:"endDate,omitempty"`
	JobSite    *string                           `json:"jobSite,omitempty"`
	StartDate  *time.Time                        `json:"startDate,omitempty"`
}

// SiteProductivityStats defines model for SiteProductivityStats.
type SiteProductivityStats struct {
	ActiveWorkers     *int     `json:"activeWorkers,omitempty"`
	AvgCompletionTime *string  `json:"avgCompletionTime,omitempty"`
	BlockedTasks      *int     `json:"blockedTasks,omitempty"`
	CompletedTasks    *int     `json:"completedTasks,omitempty"`
	CompletionRate    *float64 `json:"completionRate,omitempty"`
	TotalTasks        *int     `json:"totalTasks,omitempty"`
}

// SiteTaskDistribution defines model for SiteTaskDistribution.
type SiteTaskDistribution struct {
	EndDate     *time.Time                  `json:"endDate,omitempty"`
	JobSite     *string                     `json:"jobSite,omitempty"`
	StartDate   *time.Time                  `json:"startDate,omitempty"`
	WorkerStats *map[string]WorkerTaskStats `json:"workerStats,omitempty"`
}

// SiteUtilizationMetrics defines model for SiteUtilizationMetrics.
type SiteUtilizationMetrics struct {
	Date    *time.Time            `json:"date,omitempty"`
	JobSite *string               `json:"jobSite,omitempty"`
	Stats   *SiteUtilizationStats `json:"stats,omitempty"`
}

// SiteUtilizationStats defines model for SiteUtilizationStats.
type SiteUtilizationStats struct {
	AvgWorkDuration      *string         `json:"avgWorkDuration,omitempty"`
	CheckInDistribution  *map[string]int `json:"checkInDistribution,omitempty"`
	CheckOutDistribution *map[string]int `json:"checkOutDistribution,omitempty"`
	CompletedTasks       *int            `json:"completedTasks,omitempty"`
	LateWorkers          *int            `json:"lateWorkers,omitempty"`
	OnTimeWorkers        *int            `json:"onTimeWorkers,omitempty"`
	SiteUtilizationRate  *float64        `json:"siteUtilizationRate,omitempty"`
	TotalActiveTime      *string         `json:"totalActiveTime,omitempty"`
	TotalTasks           *int            `json:"totalTasks,omitempty"`
	TotalWorkers         *int            `json:"totalWorkers,omitempty"`
}

// TaskBlockageInfo defines model for TaskBlockageInfo.
type TaskBlockageInfo struct {
	BlockReason *string `json:"blockReason,omitempty"`
	IsBlocked   bool    `json:"isBlocked"`

	// Since Unix timestamp since the task got blocked
	Since int64 `json:"since"`
}

// TaskInfo defines model for TaskInfo.
type TaskInfo struct {
	BlockReason *string     `json:"blockReason,omitempty"`
	IsBlocked   *bool       `json:"isBlocked,omitempty"`
	StartedAt   *int64      `json:"startedAt,omitempty"`
	Status      *TaskStatus `json:"status,omitempty"`
	TaskId      *string     `json:"taskId,omitempty"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// UtilizationStats defines model for UtilizationStats.
type UtilizationStats struct {
	ActiveTime      *string  `json:"activeTime,omitempty"`
	CompletedTasks  *int     `json:"completedTasks,omitempty"`
	TotalTasks      *int     `json:"totalTasks,omitempty"`
	TotalTime       *string  `json:"totalTime,omitempty"`
	UtilizationRate *float64 `json:"utilizationRate,omitempty"`
}

// WorkerProductivityMetrics defines model for WorkerProductivityMetrics.
type WorkerProductivityMetrics struct {
	DailyStats *map[string]ProductivityStats `json:"dailyStats,omitempty"`
	EndDate    *time.Time                    `json:"endDate,omitempty"`
	StartDate  *time.Time                    `json:"startDate,omitempty"`
	WorkerId   *string                       `json:"workerId,omitempty"`
}

// WorkerTaskHistory defines model for WorkerTaskHistory.
type WorkerTaskHistory struct {
	EndDate   *time.Time            `json:"endDate,omitempty"`
	StartDate *time.Time            `json:"startDate,omitempty"`
	Tasks     *[]HistoricalTaskInfo `json:"tasks,omitempty"`
	WorkerId  *string               `json:"workerId,omitempty"`
}

// WorkerTaskStats defines model for WorkerTaskStats.
type WorkerTaskStats struct {
	AvgTaskDuration *string  `json:"avgTaskDuration,omitempty"`
	BlockedTasks    *int     `json:"blockedTasks,omitempty"`
	CompletedTasks  *int     `json:"completedTasks,omitempty"`
	CompletionRate  *float64 `json:"completionRate,omitempty"`
	TotalTasks      *int     `json:"totalTasks,omitempty"`
}

// WorkerTaskStatus defines model for WorkerTaskStatus.
type WorkerTaskStatus struct {
	// CurrentSite Job site ID where the worker is currently working
	CurrentSite     string     `json:"currentSite"`
	CurrentTasks    []TaskInfo `json:"currentTasks"`
	IsOnBreak       bool       `json:"isOnBreak"`
	IsSessionActive bool       `json:"isSessionActive"`
}

// WorkerUtilizationMetrics defines model for WorkerUtilizationMetrics.
type WorkerUtilizationMetrics struct {
	Date     time.Time         `json:"date"`
	Stats    *UtilizationStats `json:"stats,omitempty"`
	WorkerId string            `json:"workerId"`
}

// GetSiteProductivityParams defines parameters for GetSiteProductivity.
type GetSiteProductivityParams struct {
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`
	End   *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`
}

// GetSiteTaskDistributionParams defines parameters for GetSiteTaskDistribution.
type GetSiteTaskDistributionParams struct {
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`
	End   *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`
}

// GetSiteUtilizationParams defines parameters for GetSiteUtilization.
type GetSiteUtilizationParams struct {
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// GetWorkerTaskHistoryParams defines parameters for GetWorkerTaskHistory.
type GetWorkerTaskHistoryParams struct {
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`
	End   *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`
}

// GetWorkerProductivityParams defines parameters for GetWorkerProductivity.
type GetWorkerProductivityParams struct {
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`
	End   *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`
}

// GetWorkerUtilizationParams defines parameters for GetWorkerUtilization.
type GetWorkerUtilizationParams struct {
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}
