# Default values for reference-app-wms-go.

replicaCountApi: 1
replicaCountWorker: 1

image:
  repository: "your-dockerhub-namespace/reference-wms-go-server"
  tag: "latest"
  pullPolicy: "Always"

worker:
  image:
    repository: "your-dockerhub-namespace/reference-wms-go-worker"
    tag: "latest"
    pullPolicy: "Always"

service:
  type: ClusterIP
  port: 8080

# Some environment variables for the API, the Worker, or shared DB info.
env:
  DB_HOST: "postgres-host"
  DB_PORT: "5432"
  DB_USER: "myuser"
  DB_PASSWORD: "mypassword"
  DB_NAME: "wms"
  TEMPORAL_GRPC_ENDPOINT: "temporal:7233"
  # ... add any additional environment variables as needed

resourcesApi:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

resourcesWorker:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
